# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categoria das not\xedcias.',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Clientes para Solicita\xe7\xe3o de help Desk',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('repositorio_documento', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Documentos, help desk e materiais de apoio',
            },
        ),
        migrations.CreateModel(
            name='Help_Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data_requisicao', models.DateField(help_text='Data da solicita\xe7\xe3o de ajuda')),
                ('hora_requisicao', models.TimeField(help_text='Hora da solicita\xe7\xe3o de ajuda')),
                ('prioridade_da_acao', models.CharField(choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAIXA', 'BAIXA')], max_length=5)),
                ('requisitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Help_Desk, registros de solicita\xe7\xe3o de ajuda.',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data_publicacao', models.DateTimeField(auto_now=True)),
                ('destaque', models.BooleanField()),
                ('publicado', models.BooleanField()),
                ('imagem', models.FileField(blank=True, upload_to='imagens/%Y/%m/%d/')),
                ('nota', models.TextField()),
                ('categoria_da_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Categoria_noticia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Not\xedcias para disponibilizar no portal.',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Setor da Secretaria ou de \xd3rg\xe3o.',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Palavras-Chave para atribuir \xe0s not\xedcias',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('MANUAL', 'MANUAL'), ('PLANO_DE_COMUNICACAO', 'PLANO_DE_COMUNICACAO'), ('DOCUMENTO_DE_APOIO', 'DOCUMENTO_DE_APOIO')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Documento',
            },
        ),
        migrations.AddField(
            model_name='help_desk',
            name='setor_requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Setor'),
        ),
        migrations.AddField(
            model_name='help_desk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Tipo_Documento'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='setor_locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Setor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
