# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('url_video_youtube', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
