# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='credito_midia',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
