# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='credito_midia_imagem',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noticias',
            name='credito_midia_video',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noticias',
            name='legenda_da_imagem',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noticias',
            name='legenda_do_video',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noticias',
            name='video',
            field=models.FileField(blank=True, upload_to='videos_noticias/%Y/%m/%d/'),
        ),
    ]
