# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Help_Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data_requisicao', models.DateField(help_text='Data da solicita\xe7\xe3o de ajuda')),
                ('hora_requisicao', models.TimeField(help_text='Hora da solicita\xe7\xe3o de ajuda')),
                ('requisitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Setor da Secretaria ou de \xd3rg\xe3o',
            },
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name_plural': 'Documentos, help desk e materiais de apoio'},
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='url_video_youtube',
        ),
        migrations.AddField(
            model_name='documentos',
            name='repositorio_documento',
            field=models.FileField(default=1, upload_to=b'', verbose_name='documentos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='help_desk',
            name='setor_requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Setor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='setor_locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Setor'),
        ),
    ]
