# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0002_auto_20180122_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='tags_lista',
            field=models.ManyToManyField(to='app_documentos.Tag'),
        ),
    ]
