# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0002_auto_20171129_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Categoria das not\xedcias',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data_publicacao', models.DateTimeField(auto_now=True)),
                ('nota', models.TextField()),
                ('categoria_da_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documentos.Categoria_noticia')),
            ],
            options={
                'verbose_name_plural': 'Not\xedcias para disponibilizar no portal',
            },
        ),
        migrations.AlterModelOptions(
            name='help_desk',
            options={'verbose_name_plural': 'Help_Desk, registros de solicita\xe7\xe3o de ajuda'},
        ),
        migrations.AddField(
            model_name='help_desk',
            name='prioridade_da_acao',
            field=models.CharField(choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAIXA', 'BAIXA')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
