# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0003_noticias_tags_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='bigode',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noticias',
            name='chapeu',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noticias',
            name='documentos_complementares',
            field=models.FileField(blank=True, upload_to='documentos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='reporter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
