# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 19:24
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0004_auto_20180122_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='nota',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
